# Decision Tree 

In [2]:
import pandas as pd 
import numpy as  np
import matplotlib.pyplot as plt 
import seaborn as sns 

In [3]:
df = pd.read_csv("WineQT.csv")
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5


In [4]:
df.shape

(1143, 12)

In [5]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
df.columns 

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [7]:
X = df.drop(columns="quality" , axis=1)
y = df["quality"]

In [8]:
X.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [9]:
y 

0       5
1       5
2       5
3       6
4       5
       ..
1138    6
1139    6
1140    5
1141    6
1142    5
Name: quality, Length: 1143, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
prediction = model.predict(X_test)
prediction

array([4, 6, 6, 5, 5, 7, 5, 5, 5, 5, 7, 6, 6, 6, 6, 6, 6, 4, 5, 6, 7, 5,
       3, 6, 5, 5, 7, 6, 5, 6, 5, 5, 7, 5, 5, 5, 5, 6, 6, 6, 7, 6, 6, 6,
       5, 5, 5, 5, 5, 6, 6, 5, 6, 7, 6, 7, 5, 7, 7, 5, 5, 6, 6, 7, 7, 6,
       6, 6, 6, 5, 5, 6, 5, 6, 3, 5, 5, 6, 5, 5, 5, 6, 5, 3, 5, 6, 5, 6,
       7, 6, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 4, 5, 6, 6, 5, 6, 7, 6, 7,
       7, 5, 5, 5, 4, 6, 6, 8, 5, 5, 5, 6, 5, 6, 5, 6, 4, 6, 5, 6, 5, 5,
       7, 6, 5, 4, 4, 5, 5, 6, 6, 5, 5, 5, 7, 5, 5, 5, 5, 5, 6, 5, 6, 4,
       6, 5, 5, 5, 7, 6, 5, 5, 6, 6, 7, 5, 6, 3, 6, 5, 6, 5, 6, 6, 5, 6,
       6, 6, 5, 5, 7, 5, 6, 6, 5, 5, 7, 5, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6,
       7, 6, 5, 6, 5, 6, 7, 7, 5, 6, 7, 5, 3, 6, 6, 6, 5, 6, 6, 5, 7, 5,
       5, 6, 5, 5, 4, 7, 6, 6, 6])

In [23]:
model.predict([[7.5,0.52,0.42,2.3,0.7,8,38,0.9972,3.58,0.61,10.5]])

c:\Users\waghv\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([6])

Download model 

In [27]:
import pickle

pickle.dump(model , open("Wine_Model.pkl","wb"))

In [32]:
Quality_model = pickle.load(open("Wine_Model.pkl", "rb")) 

In [31]:
Quality_model.predict(X_test)

array([4, 6, 6, 5, 5, 7, 5, 5, 5, 5, 7, 6, 6, 6, 6, 6, 6, 4, 5, 6, 7, 5,
       3, 6, 5, 5, 7, 6, 5, 6, 5, 5, 7, 5, 5, 5, 5, 6, 6, 6, 7, 6, 6, 6,
       5, 5, 5, 5, 5, 6, 6, 5, 6, 7, 6, 7, 5, 7, 7, 5, 5, 6, 6, 7, 7, 6,
       6, 6, 6, 5, 5, 6, 5, 6, 3, 5, 5, 6, 5, 5, 5, 6, 5, 3, 5, 6, 5, 6,
       7, 6, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 4, 5, 6, 6, 5, 6, 7, 6, 7,
       7, 5, 5, 5, 4, 6, 6, 8, 5, 5, 5, 6, 5, 6, 5, 6, 4, 6, 5, 6, 5, 5,
       7, 6, 5, 4, 4, 5, 5, 6, 6, 5, 5, 5, 7, 5, 5, 5, 5, 5, 6, 5, 6, 4,
       6, 5, 5, 5, 7, 6, 5, 5, 6, 6, 7, 5, 6, 3, 6, 5, 6, 5, 6, 6, 5, 6,
       6, 6, 5, 5, 7, 5, 6, 6, 5, 5, 7, 5, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6,
       7, 6, 5, 6, 5, 6, 7, 7, 5, 6, 7, 5, 3, 6, 6, 6, 5, 6, 6, 5, 7, 5,
       5, 6, 5, 5, 4, 7, 6, 6, 6])